### ISSUE TITLE
Explore other indexing strategies

### ISSUE THREAD

**Issue by marino39** [go-bond/bond#66]
Please explore other potential indexing strategies that we could use in order to faster index and query large amounts of data.

Our suggestions are:
- async indexing
- range key/point key usage
- table/block property filters - https://github.com/go-bond/bond/pull/63

**Comment by poonai** [comment]
Just noting ideas here: 

We have a unique index for every record. 

eg: 

recordId, userID, NFTID
1, 1, 1
2, 2, 1 

We would create two indexes for indexing NFT ID for the above example, because we suffix the primary key as part of the index key while indexing.  This could be reduced into one index if we store the primary key as a value.

eg: 

index for NFTID_1 -> [1,2]. This reduces the number of records being written to DB and the number of records that need to be retrieved while querying.

**Comment by marino39** [comment]
I had a similar idea before. Please see attached file.

[Note 4 Aug 2022 index.pdf](https://github.com/go-bond/bond/files/10101915/Note.4.Aug.2022.index.pdf)
